apiVersion: v1
kind: Pod
metadata:
  name: db-noticias
  labels:
    app: db-noticias
spec:
  containers:
    - name: db-noticias
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306
      envFrom: # para importar tudo
        - configMapRef:
            name: db-configmap

      #env:
        #- name: MYSQL_ROOT_PASSWORD
        #  valueFrom: 
        #    configMapKeyRef:
         #     name: db-configmap
         #     key: MYSQL_ROOT_PASSWORD
        # se for para importar variaveis uma a uma