version: '3.9'
services:
  mongodb:
    image: mongo:4.4.6
    container_name: meu-mongo
    networks:
      - compose-bridge

  alurabooks:
    image: aluradocker/alura-books:1.0
    container_name: alurabooks
    networks:
      - compose-bridge
    ports:
      - 3000:3000
    depends_on:
      - mongodb

networks:
  compose-bridge:
    driver: bridge


# comando para executar o arquivo = docker compose up -d (-d para nao travar o terminal), 
# deve estra no diretório onde o arquivo .yml foi criado
# docker compose down = derruba oque foi criado
# docker compose ps = lista oque foi criado