FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /App

# # # Copy everything
 COPY . ./
# # # Restore as distinct layers
 RUN dotnet restore
# #BUILD and publish a release
RUN dotnet publish -c Release -o out

# # Build runtime image
 FROM mcr.microsoft.com/dotnet/aspnet:6.0
 WORKDIR /App
# COPY . .
COPY --from=build-env /App/out .
EXPOSE 5000
# #RUN dotnet run
# #CMD [ "dotnet", "TICKETGR.dll" ]
 CMD [ "dotnet", "TICKETGR.dll", "--urls", "http://0.0.0.0:5000" ]








