# Use a imagem oficial do Node.js como base
FROM node:20.11-alpine3.18

# Diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie o arquivo package.json e package-lock.json (se existir)
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie todo o código do projeto para o contêiner
COPY . .

# Exponha a porta 3000 (ou a porta que seu aplicativo Node.js está usando)
EXPOSE 8000

# Comando para iniciar o aplicativo quando o contêiner for executado
CMD ["npm", "start"]
